### PR TITLE
cancel timer for triggered intervals

### PR DESCRIPTION
**Pull request by uwiger**
Addresses issue #24

### CODE REVIEW

**Comment by tolbrino** [comment]
Is there a test as well?

**Comment by uwiger** [comment]
Tested it manually. For time-based tests in the test suite, we should introduce mocking of the time function (although that doesn't work on direct calls to erlang:send_after/3)

**Comment by tolbrino** [comment]
LGTM, except from the missing test case.

Calls to `erlang:send_after/3` could be replaced when testing with mockable alternatives. I didn't check what kind of an impact that would make.

**Comment by uwiger** [comment]
I have started looking into adjusting the code so that time functions are easily mockable. I think the best approach right now would be to introduce a separate module, e.g. `exometer_time.erl`, that aligns with the OTP R18 time API.

**Comment by tolbrino** [comment]
Yes, that sounds reasonable although this is yet another step of backporting some APIs to R16.

**Pull request merged**
