### PR TITLE
Add setup to the list of exometer_core applicatons

### PR DESCRIPTION
**Pull request by kellymclaughlin**
The setup application is required by exometer_core when it starts so add
it to the list of applications to ensure it is included in release
builds. This avoids applications that include exometer_core as a
dependency from having to explicitly list the setup application in a
release configuration.

### CODE REVIEW

**Comment by uwiger** [comment]
The test failure is likely due to test suite code that explicitly starts needed apps before starting exometer.

Since we have dropped support for OTP R15, that code should now be replaced by calls to `application:ensure_all_started(exometer)`. Ideally, the list of started apps should be passed to the cleanup function, which should stop them.

**Comment by kellymclaughlin** [comment]
I used `application:ensure_all_started`, but that didn't appear until R16B02 so the Travis builders with earlier R16 versions fail.

**Comment by uwiger** [comment]
Annoying. I guess we'll have to live with specifically starting each application a while longer then.

**Comment by uwiger** [comment]
I think the problem (or, at least ONE problem) lies here:
https://github.com/kellymclaughlin/exometer_core/blob/add-setup-to-applications/test/exometer_SUITE.erl#L114

It should be `exometer_test_util:ensure_all_started(exometer_core)`, as for the other cases.

**Comment by kellymclaughlin** [comment]
That got it. Nice catch! Thanks for taking a look.

**Comment by uwiger** [comment]
Great! Merged. Thanks.

**Pull request merged**
