### PR TITLE
move meck and edown to rebar3 profiles

### PR DESCRIPTION
**Pull request by tsloughter**
This patch upgrades `setup` to a rebar3 compatible version, adds the lock file and updates the gitignore for rebar3 files, moves `meck` to the test profile so it is only pulled in when `ct` or `eunit` are run and `edown` to the `docs` profile so it is only pulled down if `edocs` is run.

This does not have any effect on users of rebar2 who depend on exometer_core.

### CODE REVIEW

**Comment by tsloughter** [comment]
Ugh, nevermind, apparently rebar2 doesn't support `{ref, ...}`...

**Comment by tsloughter** [comment]
Should be good now.

**Comment by uwiger** [comment]
@tsloughter, sorry for leaving this unattended for so long. Still happy with this?

**Comment by tsloughter** [comment]
@uwiger @tolbrino thanks! I forgot about this :). seems it could still use some tweaks since one of the other deps is still pulling in stuff like meck.

**Comment by uwiger** [comment]
Yes, I noticed a few things that need some more love. My own current focus is to try to tend to the backlogs of my different project (updating exometer is next on my list), now that I have some time to do so.

**Pull request merged**
