### PR TITLE
Switch from lager to hut-based logging

### PR DESCRIPTION
**Pull request by tolbrino**
As part of the switch the `exometer_report_lager` reporter will be moved
into its own repository.

In case we agree to switch I will finalize the move of the reporter and clean up the docs as well.

### CODE REVIEW

**Comment by uwiger** [comment]
I agree that insofar as the exometer_report_lager module should exist at all, it should be in exometer_core. Personally, I think it was a mistake.

However, using lager 3.x, one could modify it to use a separate sink, and have the metrics output to a separate log. I would much prefer that.

**Comment by tolbrino** [comment]
Did you mean `should not be in exometer_core`? If not I'm a little confused :-)

**Comment by uwiger** [comment]
I mean that exometer_report_lager didn't turn out as useful as I'd hoped, but it belongs in exometer_core, not exometer.

OTOH, if we are now removing the lager dependency from exometer_core, perhaps it should *not* be in there? :)

**Comment by tolbrino** [comment]
I updated the PR to use the release of hut. Once this is merged, I can update the exometer_lager repo.

**Comment by tolbrino** [comment]
@uwiger Complaints?

**Comment by uwiger** [comment]
@tolbrino am I correct in concluding that the default behavior for `?log(debug, ...)` is to call the error_logger?

I think the appropriate default action for debug logging would be to do nothing, unless debug is enabled.

**Comment by tolbrino** [comment]
@uwiger You are correct. So far I assumed the log level checks would be the responsibility of the underlying log system. error_logger never supported such thing, lager however does.

So you'd be fine with having a simple debug toggle to enable debug logging while all other levels are passed through directly?

**Comment by uwiger** [comment]
@tolbrino I would. The lager transform inserts a check using `whereis/1` ...

**Comment by tolbrino** [comment]
@uwiger I've added something to enable debug logging to the latest https://github.com/tolbrino/hut master.

**Comment by uwiger** [comment]
Looks ok to me

**Comment by tolbrino** [comment]
I updated hut to the latest version. Feel free to merge.

**Comment by uwiger** [comment]
Shouldn't there be some mention in the documentation?

For those who used lager before and depended on exometer to pull it in (hopefully not too many), this change will require them to state the lager dependency explicitly. At the very least, they will need to insert a config to keep the lager logging behavior.

**Comment by tolbrino** [comment]
I think that kind of info would be better suited for the release notes of the next release.

**Pull request merged**
