### PR TITLE
Switch fully to rebar3 + update deps

### PR DESCRIPTION
**Pull request by uwiger**
Use rebar3 in the Makefile.
Update deps to current hex.pm versions

### CODE REVIEW

**Comment by isaacsanders** [comment]
I would be into this release if it means starting to use exometer in Elixir becomes more straightforward. As it is, I am having problems installing, and it stems from `setup` requiring a `./rebar` binary.

**Comment by uwiger** [comment]
@isaacsanders can you give me an example of what's tripping you up? I'm using `setup` in a rebar3-based project at the moment, so I'm all for fixing the necessary details.

**Comment by isaacsanders** [comment]
I get the error outlined in uwiger/setup#44.

I tried to add `exometer_core` to my `mix.exs`, and everything was able to build besides `setup`.

**Comment by uwiger** [comment]
@isaacsanders could you try https://github.com/uwiger/setup/pull/47 ?

**Comment by isaacsanders** [comment]
With these two lines in my `mix.exs`:

```elixir
     {:setup,               "~> 2.0", override: true},
     {:exometer_core,       "~> 1.5"},
```

I get this error:

```
 $ mix deps.compile setup
===> Compiling setup
===> Unable to run post hooks for 'compile', command 'escriptize' not found.
** (Mix) Could not compile dependency :setup, "~/.asdf/installs/elixir/1.5.2/.mix/rebar3 bare compile --paths "~/project/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile setup", update it with "mix deps.update setup" or clean it with "mix deps.clean setup"
```

**Comment by uwiger** [comment]
Yes, I noticed that too when I set up a simple project just for testing.

I guess there are two alternatives: either solve `escriptize` problem, or simply turn it off in this specific situation. I assume that the former would be more difficult, but OTOH be more useful.

**Comment by tolbrino** [comment]
@uwiger I adapted the PR to the latest master. The changes look fine to me.

**Comment by Argonus** [comment]
@uwiger @tolbrino 
Hi guys,
How it is going? This will be amazing in all Elixir libs ;)

**Comment by tolbrino** [comment]
Closing this since #119 was merged.

**Pull request closed without merging**
