### PR TITLE
update folsom, which adds erlang 19 support

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by getong** [comment]
I found the reason why folsom failed in 19. I make pr to folsom, see folsom-project/folsom#18. I will update this pr as the folsom-project/folsom#18 approved. Wait until then.

**Comment by getong** [comment]
@tolbrino update new tag, which works and can be merged now.

**Comment by jparise** [comment]
This upgrade would also address the mismatched `meck` versions. Folsom 0.8.2 references meck 0.8.2, while exometer_core wants meck 0.8.4. Folsom 0.8.5 moves its meck dependency forward to 0.8.4, which makes things happier.

**Comment by uwiger** [comment]
LGTM. Anyone verified that it doesn't crash and burn on OTP 18?

**Comment by uwiger** [comment]
Thanks. Merged.

**Pull request merged**
