### PR TITLE
Fix issue #90 (badarg when sending to reporter)

### PR DESCRIPTION
**Pull request by esstrifork**
Added a test case to expose the problem; implemented a fix.

### CODE REVIEW

**Comment by uwiger** [comment]
Looks pretty good. Are you done, or are more commits in the works?

**Comment by michalwski** [comment]
Any update on this? We at [esl/MongooseIM](https://github.com/esl/MongooseIM) would like to see it merged into master.

**Comment by uwiger** [comment]
Willing to merge if you guys are done.

**Comment by michalwski** [comment]
@esstrifork are you going to add something to this PR?

**Comment by uwiger** [comment]
Final ask: are you done with this PR?

**Comment by uwiger** [comment]
Merged. Thanks.

**Pull request merged**
