### PR TITLE
Reformat according to Erlang mode in Emacs

### PR DESCRIPTION
**Pull request by amiramix**
No functional changes - only reformatting to keep it compatible with the Erlang mode in Emacs

### CODE REVIEW

**Comment by uwiger** [comment]
One issue with formatting fixes is that many emacs editors (including mine, it seems) have the wrong defaults. I would like to place a `dir-locals.el` file in the `exometer_core` directory, with at least the following content:

```lisp
( (erlang-mode . ((indent-tabs-mode . nil)) ) )
```

**Comment by uwiger** [comment]
As far as I can tell from the network graph, merging this should not offend anyone, but devs with un-pushed branches may end up with a frustrating rebase.

(I have some such changes...)

**Comment by amiramix** [comment]
What do you suggest? Should I just reformat only the one file that I was fixing in the other pull request? I don't think there is any way around that, if the files are not being kept formatted then either they can be reformatted in one big commit or in stages (or not at all).

**Comment by amiramix** [comment]
BTW you are right about the formatting, I have the (setq-default indent-tabs-mode nil) in my .emacs.

**Comment by uwiger** [comment]
My suggestion is to at least give others some time to comment. Regarding functional changes in the pipeline, the choice is between merging them first, then rebasing the whitespace PR, or doing it the other way around.

**Comment by tolbrino** [comment]
If these changes are to be applied, I suggest a similar vim configuration is included as well. Otherwise, there will be plenty of otherwise unrelated syntax changes crawling in in the future.

In regards to when to apply this: I prefer doing this grand change first and then having to rebase any functional changes. Otherwise this PR will need a couple of updates in the future.

**Comment by uwiger** [comment]
I verified that the following works well on a feature branch based on master before whitespace changes:

```sh
git remote add yoonka git://github.com/yoonka/exometer_core.git
git rebase --ignore-whitespace yoonka/master-formatting
```

**Comment by amiramix** [comment]
Great, thanks for the tip about --ignore-whitespace!

**Pull request merged**
