### PR TITLE
More timing-robust test execution

### PR DESCRIPTION
**Pull request by uwiger**
Make more use of the majority() function in the test suites
Use 5 attempts as the default when using majority/2
Increase timeout in the reporting test

### CODE REVIEW

**Comment by uwiger** [comment]
Lately, we have seen intermittent errors in Travis-CI for practically every commit. For this PR, I have executed the full Travis-CI suite 3 times without a single error. The changes do seem to have improved things.

**Comment by uwiger** [comment]
On the fourth run, there were some addrinuse errors. I've made sure to include `{reuseaddr,true}` by default in the test logger, and also have the udp input process monitor the logger and terminate when it gets a `'DOWN'` message.

**Comment by tolbrino** [comment]
I've still experienced errors locally, thus the changes to the branch. I'll check why some tests fail for me.

**Comment by uwiger** [comment]
At least it's getting a lot better! ;-)

**Comment by tolbrino** [comment]
This is good to merge from my perspective.

**Pull request merged**
