### PR TITLE
Adapt histogram slot period

### PR DESCRIPTION
**Pull request by tolbrino**
This is an alternative to #39

### CODE REVIEW

**Comment by uwiger** [comment]
@tolbrino could you resolve the conflict and verify that the test suite passes?

**Comment by uwiger** [comment]
Ping @tolbrino

**Comment by tolbrino** [comment]
I rebased the PR on the latest master.

**Comment by uwiger** [comment]
Ok, just awaiting the CI results for good measure.

**Comment by uwiger** [comment]
Merged. Thanks.

**Pull request merged**
